-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 10:58:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auberge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auberge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auberge` DEFAULT CHARACTER SET utf8 ;
USE `auberge` ;

-- -----------------------------------------------------
-- Table `auberge`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `statut` ENUM('prof', 'eleve', 'admin') NULL,
  `avatar` VARCHAR(255) NULL,
  `semestre` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `nom_ecole` VARCHAR(45) NULL,
  `actif` ENUM('up', 'down', 'ban') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `resume` VARCHAR(45) NULL,
  `entreprise` VARCHAR(45) NULL,
  `datepublication` DATETIME NULL,
  `semestre` VARCHAR(45) NULL,
  `statut` ENUM('dispo', 'qualifié', 'affecté') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`Ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`Ip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `free` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`user_has_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`user_has_groupe` (
  `user_id` INT NOT NULL,
  `groupe_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_user_has_projet_user_idx` (`user_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_projet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `auberge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`groupe` (
  `port` INT NOT NULL,
  `statut` ENUM('dispo', 'qualifié', 'affecté') NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `projet_id` INT NOT NULL,
  `Ip_id` INT NOT NULL,
  `user_has_groupe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groupe_projet1_idx` (`projet_id` ASC) ,
  INDEX `fk_groupe_Ip1_idx` (`Ip_id` ASC) ,
  INDEX `fk_groupe_user_has_groupe1_idx` (`user_has_groupe_id` ASC) ,
  CONSTRAINT `fk_groupe_projet1`
    FOREIGN KEY (`projet_id`)
    REFERENCES `auberge`.`projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_Ip1`
    FOREIGN KEY (`Ip_id`)
    REFERENCES `auberge`.`Ip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_user_has_groupe1`
    FOREIGN KEY (`user_has_groupe_id`)
    REFERENCES `auberge`.`user_has_groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
