-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 11:29:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auberge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auberge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auberge` DEFAULT CHARACTER SET utf8 ;
USE `auberge` ;

-- -----------------------------------------------------
-- Table `auberge`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `statut` ENUM('prof', 'eleve', 'admin') NULL,
  `avatar` VARCHAR(255) NULL,
  `semestre` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `nom_ecole` VARCHAR(45) NULL,
  `actif` ENUM('up', 'down', 'ban') NOT NULL,
  `disponible` ENUM('y', 'n') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `resume` VARCHAR(45) NULL,
  `entreprise` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  `datepublication` DATETIME NULL,
  `statut` ENUM('dispo', 'qualifié', 'affecté') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`Ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`Ip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `free` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`groupe` (
  `port` INT NOT NULL,
  
  `id` INT NOT NULL AUTO_INCREMENT,
  `projet_id` INT NOT NULL,
  `Ip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groupe_projet1_idx` (`projet_id` ASC) ,
  INDEX `fk_groupe_Ip1_idx` (`Ip_id` ASC) ,
  CONSTRAINT `fk_groupe_projet1`
    FOREIGN KEY (`projet_id`)
    REFERENCES `auberge`.`projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_Ip1`
    FOREIGN KEY (`Ip_id`)
    REFERENCES `auberge`.`Ip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auberge`.`user_has_groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auberge`.`user_has_groupe` (
  `user_id` INT NOT NULL,
  `groupe_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_groupe_groupe1_idx` (`groupe_id` ASC) ,
  INDEX `fk_user_has_groupe_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_user_has_groupe_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auberge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_groupe_groupe1`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `auberge`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE `auberge`;
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'a', NULL , 'prof', NULL, 'Patrice', 'Patoche', 'intech', 'down');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL , 'isma@intechinfo.fr', 'isma49', 'eleve', NULL, 'Nimzill', 'ismael', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'ben@intechinfo.fr', 'root', 'admin', NULL, 'Rodriguez', 'Benjamin ', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'yann@intechinfo.fr', 'root', 'admin', NULL, 'Simachel', 'Yann', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'erwan@intehcinfo.fr', 'root', 'admin', NULL, 'Hacques', 'Erwan', 'intech ', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'olive@intechinfo.fr', 'test', 'eleve', NULL, 'Lespagnon', 'olivier', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'coco@intechinfo.fr', 'coco', 'prof', NULL, 'Toto', 'coco', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL , 'chris@intechinfo.fr', 'red', 'eleve', NULL, 'Delcourt', 'christopher', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'nahel@intechinfo.fr', 'test', 'entreprise', NULL, 'Master', 'Nahel', 'intech', 'up');
INSERT INTO `auberge`.`user` (`id`, `mail`, `password`, `statut`, `avatar`, `nom`, `prenom`, `nom_ecole`, `actif`) VALUES (NULL, 'ed@intechinfo.fr', 'ed', 'eleve', NULL, 'ed', 'momo', 'intech', 'up');

COMMIT;


-- -----------------------------------------------------
-- Data for table `auberge`.`projet`
-- -----------------------------------------------------
START TRANSACTION;
USE `auberge`;
INSERT INTO `auberge`.`projet` (`id`, `nom`, `statut`) VALUES (NULL, 'un', 'dispo');
INSERT INTO `auberge`.`projet` (`id`, `nom`, `statut`) VALUES (NULL, 'deux', 'dispo');
INSERT INTO `auberge`.`projet` (`id`, `nom`, `statut`) VALUES (NULL, 'trois', 'dispo');

COMMIT;



